# Site settings
title: Corey Hulen
email: corey@hulen.com
description: "Corey Hulen is Founder and CTO of Tempo AI a SRI (Stanford Research Institute) incubated company. Previously, Corey was founder and Chief Architect of Pricini.com a web 2.0 internet technology company focusing on the consumer analytics space."
url: "http://coreyhulen.github.io"
username: coreyhulen
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
